// src/components/Search.vue
<script setup lang="ts">
import Button from '@/components/ui/button/Button.vue'
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import { SearchIcon } from 'lucide-vue-next'
import { ref } from 'vue'

interface Props {
  groups?: {
    heading?: string
    links?: {
      text?: string
      href?: string
    }[]
  }[]
}

const { groups } = defineProps<Props>()

const open = ref(false)

function handleOpenChange() {
  open.value = !open.value
}
</script>

<template>
  <Button
    @click="handleOpenChange"
    size="sm"
    class="gap-8"
    variant="outline"
  >
    Zoeken...
    <SearchIcon />
  </Button>
  <CommandDialog v-model:open="open">
    <CommandInput placeholder="Typ om te zoeken..." />
    <CommandList>
      <CommandEmpty>Geen resultaten gevonden.</CommandEmpty>
      <CommandGroup
        v-for="group in groups"
        :key="group.heading"
        :heading="group.heading"
      >
        <CommandItem
          v-for="item in group.links"
          :key="item.text"
          :value="item.text ?? ''"
          as-child
        >
          <a :href="item.href">
            {{ item.text }}
          </a>
        </CommandItem>
      </CommandGroup>
    </CommandList>
  </CommandDialog>
</template>

// src/components/composite/search.tsx
import { Button } from '@/components/ui/button'
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import * as React from 'react'

interface Props {
  groups?: {
    heading?: string
    links?: {
      text?: string
      href?: string
    }[]
  }[]
}

export function Search({ groups }: Props) {
  const [open, setOpen] = React.useState(false)

  return (
    <>
      <Button
        variant="outline"
        onClick={() => setOpen(true)}
      >
        Typ om te zoeken...
      </Button>
      <CommandDialog
        open={open}
        onOpenChange={setOpen}
      >
        <CommandInput placeholder="Type a command or search..." />
        <CommandList>
          <CommandEmpty>Geen resultaten gevonden.</CommandEmpty>
          {groups?.map(({ heading, links }) => (
            <CommandGroup heading={heading}>
              {links?.map(({ text, href }, index) => (
                <a
                  href={href || undefined}
                  key={index}
                >
                  <CommandItem>{text}</CommandItem>
                </a>
              ))}
            </CommandGroup>
          ))}
        </CommandList>
      </CommandDialog>
    </>
  )
}
