// src/components/Accordion.vue
<script setup lang="ts">
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'

interface Props {
  items?: {
    title?: string
    description?: string
  }[]
}

const { items } = defineProps<Props>()
</script>

<template v-if="items">
  <Accordion
    type="single"
    class="w-full max-w-xl"
    collapsible
  >
    <AccordionItem
      v-for="item in items"
      :key="item.title"
      :value="item.title ?? ''"
    >
      <AccordionTrigger>{{ item.title }}</AccordionTrigger>
      <AccordionContent>
        {{ item.description }}
      </AccordionContent>
    </AccordionItem>
  </Accordion>
</template>

// src/components/Accordion.tsx
import {
  AccordionContent,
  AccordionItem,
  Accordion as AccordionRoot,
  AccordionTrigger,
} from '@/components/ui/accordion'
import { cn } from '@/lib/utils'
import type { ComponentProps } from 'react'

interface Props {
  type?: ComponentProps<typeof AccordionRoot>['type']
  collapsible?: boolean
  class?: string
  items?: {
    title?: string
    description?: string
  }[]
}

export function Accordion({ items, class: className, type = 'single', collapsible = true }: Props) {
  return (
    items && (
      <AccordionRoot
        type={type}
        collapsible={collapsible}
        className={cn('w-full max-w-xl', className)}
      >
        {items?.map((item, index) => (
          <AccordionItem
            value={`item-${index}`}
            key={`item-${index}`}
          >
            <AccordionTrigger>{item.title}</AccordionTrigger>
            <AccordionContent>{item.description}</AccordionContent>
          </AccordionItem>
        ))}
      </AccordionRoot>
    )
  )
}
