// src/components/composite/carousel.tsx
import {
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
  Carousel as CarouselRoot,
} from '@/components/ui/carousel'
import parseReact from 'html-react-parser'
import { parse as parseNode } from 'node-html-parser'

interface Props {
  children: any
}

export function Carousel({ children }: Props) {
  // TODO: typesafe als also working for non-astro use
  const value = children.props.value
  const root = parseNode(value)
  const items = root.children.map((child) => child.outerHTML)

  return (
    items && (
      <CarouselRoot>
        <CarouselContent>
          {items.map((item, index) => (
            <CarouselItem key={index}>{parseReact(item)}</CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </CarouselRoot>
    )
  )
}

// src/components/Carousel.vue
<script setup lang="ts">
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '@/components/ui/carousel'
import { parse } from 'node-html-parser'
import { renderToString } from 'vue/server-renderer'

interface Props {
  itemClass?: string
}

const { itemClass } = defineProps<Props>()

const slots = defineSlots<{
  default(): any
}>()

const slot = slots['default']()[0]
const html = await renderToString(slot)
const root = parse(html)
const container = root.querySelector('astro-static-slot') || root.querySelector('astro-slot') || root
const children = container.children
const htmlItems = children.map((child) => child.outerHTML)
</script>

<template>
  <Carousel v-slot="{ canScrollNext }">
    <CarouselContent>
      <CarouselItem
        v-for="(htmlItem, index) in htmlItems"
        :key="index"
        :class="itemClass"
      >
        <div v-html="htmlItem" />
      </CarouselItem>
    </CarouselContent>
    <CarouselPrevious />
    <CarouselNext v-if="canScrollNext" />
  </Carousel>
</template>
