// src/components/Drawer.tsx
import { Button } from '@/components/ui/button'
import { DrawerContent, Drawer as DrawerRoot, DrawerTrigger } from '@/components/ui/drawer'
import { cn } from '@/lib/utils'
import type { ComponentProps, ReactNode } from 'react'

interface Props {
  class?: string
  variant?: ComponentProps<typeof Button>['variant']
  size?: ComponentProps<typeof Button>['size']
  children?: ReactNode
  trigger?: ReactNode
}

function Drawer({ children, trigger, variant, size, class: className }: Props) {
  return (
    <DrawerRoot>
      <DrawerTrigger asChild>
        <Button
          className={cn('size-8', className)}
          variant={variant}
          size={size}
          name="drawer-trigger"
        >
          {trigger}
        </Button>
      </DrawerTrigger>
      <DrawerContent className="max-h-[60svh] p-0">{children}</DrawerContent>
    </DrawerRoot>
  )
}

export default Drawer

// src/components/Drawer.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import {
  Drawer,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from '@/components/ui/drawer'
import type { HTMLAttributes } from 'vue'

interface Props {
  class?: HTMLAttributes['class']
  button?: {
    text?: string
    variant?: 'default' | 'secondary' | 'outline' | 'ghost'
    size?: 'default' | 'sm' | 'lg'
  }
  title?: string
  description?: string
}

const { button, title, description, class: className } = defineProps<Props>()
</script>

<template>
  <Drawer>
    <DrawerTrigger as-child>
      <Button
        :variant="button?.variant"
        :size="button?.size"
        :class="className"
        name="drawer-trigger"
      >
        {{ button?.text }}
        <slot name="trigger" />
      </Button>
    </DrawerTrigger>
    <DrawerContent>
      <DrawerHeader>
        <DrawerTitle>{{ title }}</DrawerTitle>
        <DrawerDescription>{{ description }}</DrawerDescription>
        <slot name="header" />
      </DrawerHeader>
      <slot />
      <DrawerFooter>
        <slot name="footer" />
      </DrawerFooter>
    </DrawerContent>
  </Drawer>
</template>
