// src/components/composite/drawer.tsx
import { Button, type ButtonProps } from '@/components/ui/button'
import {
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  Drawer as DrawerRoot,
  DrawerTitle,
  DrawerTrigger,
} from '@/components/ui/drawer'

interface Props {
  className?: string
  variant?: ButtonProps['variant']
  size?: ButtonProps['size']
  title?: string
  description?: string
  children?: any
  trigger?: any
  header?: any
  footer?: any
}

export function Drawer({ variant, size, title, description, className, children, trigger, header, footer }: Props) {
  return (
    <DrawerRoot>
      <DrawerTrigger asChild>
        <Button
          variant={variant}
          size={size}
          className={className}
          name="drawer-trigger"
        >
          {trigger}
        </Button>
      </DrawerTrigger>
      <DrawerContent>
        <DrawerHeader>
          <DrawerTitle>{title}</DrawerTitle>
          <DrawerDescription>{description}</DrawerDescription>
          {header}
        </DrawerHeader>
        {children}
        <DrawerFooter>{footer}</DrawerFooter>
      </DrawerContent>
    </DrawerRoot>
  )
}

// src/components/Drawer.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import {
  Drawer,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from '@/components/ui/drawer'
import type { HTMLAttributes } from 'vue'

interface Props {
  class?: HTMLAttributes['class']
  button?: {
    text?: string
    variant?: 'default' | 'secondary' | 'outline' | 'ghost'
    size?: 'default' | 'sm' | 'lg'
  }
  title?: string
  description?: string
}

const { button, title, description, class: className } = defineProps<Props>()
</script>

<template>
  <Drawer>
    <DrawerTrigger as-child>
      <Button
        :variant="button?.variant"
        :size="button?.size"
        :class="className"
        name="drawer-trigger"
      >
        {{ button?.text }}
        <slot name="trigger" />
      </Button>
    </DrawerTrigger>
    <DrawerContent>
      <DrawerHeader>
        <DrawerTitle>{{ title }}</DrawerTitle>
        <DrawerDescription>{{ description }}</DrawerDescription>
        <slot name="header" />
      </DrawerHeader>
      <slot />
      <DrawerFooter>
        <slot name="footer" />
      </DrawerFooter>
    </DrawerContent>
  </Drawer>
</template>
