// src/components/gallery.tsx
import * as React from "react"

import { cn } from "@/lib/utils"
import {
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
  Carousel as CarouselRoot,
  type CarouselApi,
} from "@/components/ui/carousel"

import { Image } from "./ui/image"

interface Props extends React.ComponentProps<"div"> {
  images?: React.ComponentProps<typeof Image>[]
}

function Gallery({ images, className, ...props }: Props) {
  const [emblaMainApi, setEmblaMainApi] = React.useState<CarouselApi>()
  const [emblaThumbnailApi, setEmblaThumbnailApi] =
    React.useState<CarouselApi>()
  const [selectedIndex, setSelectedIndex] = React.useState(0)

  React.useEffect(() => {
    if (!emblaMainApi || !emblaThumbnailApi) return

    const onSelect = () => {
      setSelectedIndex(emblaMainApi.selectedScrollSnap())
      emblaThumbnailApi.scrollTo(emblaMainApi.selectedScrollSnap())
    }

    emblaMainApi.on("select", onSelect)
    emblaMainApi.on("reInit", onSelect)

    // Initial selection
    onSelect()

    return () => {
      emblaMainApi.off("select", onSelect)
      emblaMainApi.off("reInit", onSelect)
    }
  }, [emblaMainApi, emblaThumbnailApi])

  const onThumbClick = (index: number) => {
    if (!emblaMainApi) return
    emblaMainApi.scrollTo(index)
  }

  return (
    images && (
      <div
        className={cn("gallery bg-muted flex w-full flex-col pb-2", className)}
        {...props}
      >
        <CarouselRoot className="relative" setApi={setEmblaMainApi}>
          <CarouselContent className="mt-4 mr-4 mb-2 ml-0">
            {images.map((image) => (
              <CarouselItem className="pl-4" key={image.src}>
                <Image className="rounded-md" {...image} />
              </CarouselItem>
            ))}
          </CarouselContent>
          {images.length > 1 && (
            <>
              <CarouselPrevious className="left-1 max-md:hidden" />
              <CarouselNext className="right-1 max-md:hidden" />
            </>
          )}
        </CarouselRoot>
        {images.length > 1 && (
          <CarouselRoot setApi={setEmblaThumbnailApi}>
            <CarouselContent className="mr-4 ml-2 flex">
              {images.map((image, index) => (
                <CarouselItem className="basis-1/5 pl-2" key={image.src}>
                  <Image
                    className={cn(
                      "my-2 cursor-pointer rounded-sm ring-1 ring-transparent",
                      {
                        "ring-ring": index === selectedIndex,
                      }
                    )}
                    onClick={() => onThumbClick(index)}
                    {...image}
                  />
                </CarouselItem>
              ))}
            </CarouselContent>
          </CarouselRoot>
        )}
      </div>
    )
  )
}

export { Gallery }

// src/components/Gallery.vue
<script setup lang="ts">
import {
  Carousel,
  type CarouselApi,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel'
import { watchOnce } from '@vueuse/core'
import { parse } from 'node-html-parser'
import { ref } from 'vue'
import { renderToString } from 'vue/server-renderer'

const emblaMainApi = ref<CarouselApi>()
const emblaThumbnailApi = ref<CarouselApi>()
const selectedIndex = ref(0)

function onSelect() {
  if (!emblaMainApi.value || !emblaThumbnailApi.value) return
  selectedIndex.value = emblaMainApi.value.selectedScrollSnap()
  emblaThumbnailApi.value.scrollTo(emblaMainApi.value.selectedScrollSnap())
}

function onThumbClick(index: number) {
  if (!emblaMainApi.value || !emblaThumbnailApi.value) return
  emblaMainApi.value.scrollTo(index)
}

watchOnce(emblaMainApi, (emblaMainApi) => {
  if (!emblaMainApi) return

  onSelect()
  emblaMainApi.on('select', onSelect)
  emblaMainApi.on('reInit', onSelect)
})

const slots = defineSlots<{
  default(): any
}>()

const slot = slots['default']()[0]
const html = await renderToString(slot)
const root = parse(html)
const container = root.querySelector('astro-static-slot') || root.querySelector('astro-slot') || root
const children = container.children
const htmlItems = children.map((child) => child.outerHTML)
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <Carousel
      class="relative"
      @init-api="(val) => (emblaMainApi = val)"
    >
      <CarouselContent>
        <CarouselItem
          v-for="(htmlItem, index) in htmlItems"
          :key="index"
          class="rounded-md overflow-hidden"
        >
          <div v-html="htmlItem" />
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious class="left-2" />
      <CarouselNext class="right-2" />
    </Carousel>
    <Carousel
      class="relative w-full"
      @init-api="(val) => (emblaThumbnailApi = val)"
    >
      <CarouselContent class="flex gap-2 ml-0">
        <CarouselItem
          v-for="(htmlItem, index) in htmlItems"
          :key="index"
          class="pl-0 basis-1/5 cursor-pointer border rounded-md overflow-hidden"
          :class="index === selectedIndex ? 'border-ring' : ''"
          @click="onThumbClick(index)"
        >
          <div v-html="htmlItem" />
        </CarouselItem>
      </CarouselContent>
    </Carousel>
  </div>
</template>
