// src/components/composite/gallery.tsx
import {
  type CarouselApi,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
  Carousel as CarouselRoot,
} from '@/components/ui/carousel'
import parseReact from 'html-react-parser'
import { parse as parseNode } from 'node-html-parser'
import { useEffect, useState } from 'react'

interface Props {
  children: any
}

export function Gallery({ children }: Props) {
  const [emblaMainApi, setEmblaMainApi] = useState<CarouselApi>()
  const [emblaThumbnailApi, setEmblaThumbnailApi] = useState<CarouselApi>()
  const [selectedIndex, setSelectedIndex] = useState(0)

  // Parse children to get HTML items
  const value = children.props?.value
  const root = parseNode(value)
  const items = root.children.map((child) => child.outerHTML)

  useEffect(() => {
    if (!emblaMainApi || !emblaThumbnailApi) return

    const onSelect = () => {
      setSelectedIndex(emblaMainApi.selectedScrollSnap())
      emblaThumbnailApi.scrollTo(emblaMainApi.selectedScrollSnap())
    }

    emblaMainApi.on('select', onSelect)
    emblaMainApi.on('reInit', onSelect)

    // Initial selection
    onSelect()

    return () => {
      emblaMainApi.off('select', onSelect)
      emblaMainApi.off('reInit', onSelect)
    }
  }, [emblaMainApi, emblaThumbnailApi])

  const onThumbClick = (index: number) => {
    if (!emblaMainApi) return
    emblaMainApi.scrollTo(index)
  }

  return (
    <div className="w-full flex flex-col gap-2">
      <CarouselRoot
        className="relative"
        setApi={setEmblaMainApi}
      >
        <CarouselContent>
          {items.map((item, index) => (
            <CarouselItem
              key={index}
              className="rounded-md overflow-hidden"
            >
              {parseReact(item)}
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious className="left-2" />
        <CarouselNext className="right-2" />
      </CarouselRoot>

      <CarouselRoot setApi={setEmblaThumbnailApi}>
        <CarouselContent className="flex gap-2 ml-0">
          {items.map((item, index) => (
            <CarouselItem
              key={index}
              className={`pl-0 basis-1/5 cursor-pointer border rounded-md overflow-hidden ${
                index === selectedIndex ? 'border-ring border-2' : ''
              }`}
              onClick={() => onThumbClick(index)}
            >
              {parseReact(item)}
            </CarouselItem>
          ))}
        </CarouselContent>
      </CarouselRoot>
    </div>
  )
}

// src/components/Gallery.vue
<script setup lang="ts">
import {
  Carousel,
  type CarouselApi,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel'
import { watchOnce } from '@vueuse/core'
import { parse } from 'node-html-parser'
import { ref } from 'vue'
import { renderToString } from 'vue/server-renderer'

const emblaMainApi = ref<CarouselApi>()
const emblaThumbnailApi = ref<CarouselApi>()
const selectedIndex = ref(0)

function onSelect() {
  if (!emblaMainApi.value || !emblaThumbnailApi.value) return
  selectedIndex.value = emblaMainApi.value.selectedScrollSnap()
  emblaThumbnailApi.value.scrollTo(emblaMainApi.value.selectedScrollSnap())
}

function onThumbClick(index: number) {
  if (!emblaMainApi.value || !emblaThumbnailApi.value) return
  emblaMainApi.value.scrollTo(index)
}

watchOnce(emblaMainApi, (emblaMainApi) => {
  if (!emblaMainApi) return

  onSelect()
  emblaMainApi.on('select', onSelect)
  emblaMainApi.on('reInit', onSelect)
})

const slots = defineSlots<{
  default(): any
}>()

const slot = slots['default']()[0]
const html = await renderToString(slot)
const root = parse(html)
const container = root.querySelector('astro-static-slot') || root.querySelector('astro-slot') || root
const children = container.children
const htmlItems = children.map((child) => child.outerHTML)
</script>

<template>
  <div class="w-full flex flex-col gap-2">
    <Carousel
      class="relative"
      @init-api="(val) => (emblaMainApi = val)"
    >
      <CarouselContent>
        <CarouselItem
          v-for="(htmlItem, index) in htmlItems"
          :key="index"
          class="rounded-md overflow-hidden"
        >
          <div v-html="htmlItem" />
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious class="left-2" />
      <CarouselNext class="right-2" />
    </Carousel>
    <Carousel
      class="relative w-full"
      @init-api="(val) => (emblaThumbnailApi = val)"
    >
      <CarouselContent class="flex gap-2 ml-0">
        <CarouselItem
          v-for="(htmlItem, index) in htmlItems"
          :key="index"
          class="pl-0 basis-1/5 cursor-pointer border rounded-md overflow-hidden"
          :class="index === selectedIndex ? 'border-ring' : ''"
          @click="onThumbClick(index)"
        >
          <div v-html="htmlItem" />
        </CarouselItem>
      </CarouselContent>
    </Carousel>
  </div>
</template>
