// src/components/Search.vue
<script setup lang="ts">
import Button from '@/components/ui/button/Button.vue'
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import { SearchIcon } from 'lucide-vue-next'
import { ref } from 'vue'

interface Props {
  groups?: {
    heading?: string
    links?: {
      text?: string
      href?: string
    }[]
  }[]
}

const { groups } = defineProps<Props>()

const open = ref(false)

function handleOpenChange() {
  open.value = !open.value
}
</script>

<template>
  <Button
    @click="handleOpenChange"
    size="sm"
    class="gap-8 text-foreground"
    variant="outline"
  >
    Zoeken...
    <SearchIcon />
  </Button>
  <CommandDialog v-model:open="open">
    <CommandInput placeholder="Typ om te zoeken..." />
    <CommandList>
      <CommandEmpty>Geen resultaten gevonden.</CommandEmpty>
      <CommandGroup
        v-for="group in groups"
        :key="group.heading"
        :heading="group.heading"
      >
        <CommandItem
          v-for="item in group.links"
          :key="item.text"
          :value="item.text ?? ''"
          as-child
        >
          <a :href="item.href">
            {{ item.text }}
          </a>
        </CommandItem>
      </CommandGroup>
    </CommandList>
  </CommandDialog>
</template>

// src/components/search.tsx
import * as React from "react"
import { Search as SearchIcon } from "lucide-react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command"

interface Props extends React.ComponentProps<typeof Button> {
  links?: {
    text?: string
    href?: string
  }[]
}

function Search({ links, className, ...props }: Props) {
  const [open, setOpen] = React.useState(false)

  return links ? (
    <>
      <Button
        className={cn(
          "bg-muted/50 text-muted-foreground flex-grow-1 justify-between text-sm font-normal shadow-none",
          className
        )}
        variant="outline"
        {...props}
        onClick={() => setOpen(true)}
      >
        <span>Zoek door alles...</span>
        <SearchIcon className="ml-4 size-4.5" />
      </Button>
      <CommandDialog open={open} onOpenChange={setOpen}>
        <CommandInput placeholder="Zoek door alles..." />
        <CommandList>
          <CommandEmpty>Geen resultaten gevonden.</CommandEmpty>
          <CommandGroup>
            {links?.map(({ text, href }) =>
              text && href ? (
                <CommandItem
                  key={href}
                  asChild
                  onSelect={() => href && (window.location.href = href)}
                >
                  <a href={href}>{text}</a>
                </CommandItem>
              ) : null
            )}
          </CommandGroup>
        </CommandList>
      </CommandDialog>
    </>
  ) : null
}

export { Search }
