// src/components/Search.tsx
import { Button } from '@/components/ui/button'
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import { cn } from '@/lib/utils'
import { Search as SearchIcon } from 'lucide-react'
import type { ComponentProps } from 'react'
import { useState } from 'react'

interface Props {
  className?: string
  variant?: ComponentProps<typeof Button>['variant']
  size?: ComponentProps<typeof Button>['size']
  groups?: {
    heading?: string
    links?: {
      text?: string
      href?: string
    }[]
  }[]
}

function Search({ groups, variant, size, className }: Props) {
  const [open, setOpen] = useState(false)

  return (
    groups && (
      <>
        <Button
          className={cn('border border-input', className)}
          variant={variant}
          size={size}
          onClick={() => setOpen(true)}
        >
          Zoeken...
          <SearchIcon className="ml-4" />
        </Button>
        <CommandDialog
          open={open}
          onOpenChange={setOpen}
        >
          <CommandInput placeholder="Begin met zoeken..." />
          <CommandList>
            <CommandEmpty>Geen resultaten gevonden.</CommandEmpty>
            {groups?.map(({ heading, links }) => (
              <CommandGroup heading={heading}>
                {links?.map(({ text, href }, index) => (
                  <CommandItem
                    key={index}
                    asChild
                    onSelect={() => href && (window.location.href = href)}
                  >
                    <a
                      key={index}
                      href={href || undefined}
                    >
                      {text}
                    </a>
                  </CommandItem>
                ))}
              </CommandGroup>
            ))}
          </CommandList>
        </CommandDialog>
      </>
    )
  )
}

export { Search }

// src/components/Search.vue
<script setup lang="ts">
import Button from '@/components/ui/button/Button.vue'
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import { SearchIcon } from 'lucide-vue-next'
import { ref } from 'vue'

interface Props {
  groups?: {
    heading?: string
    links?: {
      text?: string
      href?: string
    }[]
  }[]
}

const { groups } = defineProps<Props>()

const open = ref(false)

function handleOpenChange() {
  open.value = !open.value
}
</script>

<template>
  <Button
    @click="handleOpenChange"
    size="sm"
    class="gap-8"
    variant="outline"
  >
    Zoeken...
    <SearchIcon />
  </Button>
  <CommandDialog v-model:open="open">
    <CommandInput placeholder="Typ om te zoeken..." />
    <CommandList>
      <CommandEmpty>Geen resultaten gevonden.</CommandEmpty>
      <CommandGroup
        v-for="group in groups"
        :key="group.heading"
        :heading="group.heading"
      >
        <CommandItem
          v-for="item in group.links"
          :key="item.text"
          :value="item.text ?? ''"
          as-child
        >
          <a :href="item.href">
            {{ item.text }}
          </a>
        </CommandItem>
      </CommandGroup>
    </CommandList>
  </CommandDialog>
</template>
